# Generated by Django 4.1.1 on 2023-01-04 04:50

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userdetailmodel_welcome_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetailmodel',
            name='cv_link',
        ),
        migrations.AddField(
            model_name='userdetailmodel',
            name='cv_file',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='raw/'),
        ),
    ]
