# Generated by Django 4.1.1 on 2023-01-04 04:52

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userdetailmodel_cv_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailmodel',
            name='cv_file',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='raw/'),
        ),
    ]
