# Generated by Django 4.1.1 on 2023-01-04 06:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userdetailmodel_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailmodel',
            name='cv_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
