# Generated by Django 4.1.1 on 2023-01-04 06:14

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userdetailmodel_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailmodel',
            name='cv_file',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='raw/'),
        ),
    ]
