# Generated by Django 4.1.1 on 2023-01-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_userdetailmodel_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailmodel',
            name='welcome_description',
            field=models.TextField(max_length=1000),
        ),
    ]
