# Generated by Django 4.1.1 on 2023-01-05 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_blog_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experienceinput',
            name='experience',
        ),
        migrations.AddField(
            model_name='experience',
            name='experiences',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='experience_inputs', to='core.experienceinput'),
            preserve_default=False,
        ),
    ]
