# Generated by Django 4.1.1 on 2023-01-05 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_experienceinput_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='experiences',
        ),
        migrations.AddField(
            model_name='experienceinput',
            name='experience',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='experience_inputs', to='core.experience'),
            preserve_default=False,
        ),
    ]
