# Generated by Django 4.1.1 on 2023-01-05 04:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_experience_experiences_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(max_length=255, upload_to='images')),
            ],
            options={
                'verbose_name': 'SkillCategory',
                'verbose_name_plural': 'SkillCategorys',
            },
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='userdetailmodel',
            options={'verbose_name': 'UserDetail', 'verbose_name_plural': 'UserDetails'},
        ),
        migrations.AlterModelOptions(
            name='usersociallink',
            options={'verbose_name': 'UserSocialLink', 'verbose_name_plural': 'UserSocialLinks'},
        ),
        migrations.AddField(
            model_name='projecttool',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecttool',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, max_length=255, upload_to='images'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skillcategory')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
    ]
